Algoritmo "Atividade1_Correntista"
// 1) Crie um algoritmo que lê o nome de um correntista, sua agência e
//conta. Exiba esses dados na tela
Var
   nome, agencia, conta: caractere


Inicio
   Escreva ("Digite o nome: ")
   Leia (nome)
   Escreva ("Digite sua agência: ")
   Leia (agencia)
   Escreva ("Digite a conta: ")
   Leia (conta)
   EscrevaL ("Informações do Correntista:")
   EscrevaL (nome)
   EscrevaL (agencia)
   EscrevaL (conta)


Fimalgoritmo