Algoritmo "EXERCICIO4_Idade"
// 4) Crie um algoritmo que lê o ano atual e o ano em que uma pessoa
//nasceu. Calcule a idade dessa pessoa e imprima o resultado na tela.
Var
   anoatual, nascimento, idade: inteiro


Inicio
   Escreva ("Digite o ano atual: ")
   Leia (anoatual)
   Escreva ("Digite o ano de nascimento: ")
   Leia (nascimento)
   idade <- anoatual-nascimento
   Escreva (" A idade é de :", idade, " anos")


Fimalgoritmo