Algoritmo "Ex2_Aula2_POSITIVO_NEGATIVO"
// 2) Escreva um programa que leia um número inteiro. Se o número lido for
//positivo, escreva uma mensagem indicando se ele é par ou ímpar.
//Se o número for negativo, escreva a seguinte mensagem:
//"Este número não é positivo".
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo